spring:
  config:
    activate:
      on-profile: prod

dentalcare:
  openapi:
    public-access: false
  jwt:
    cookie-secure: true

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
