package com.dentalcare.api.modules.audit.service;

public final class AuditActions {
    private AuditActions() { }
    public static final String AUTH_LOGIN_SUCCEEDED="AUTH_LOGIN_SUCCEEDED", AUTH_LOGIN_FAILED="AUTH_LOGIN_FAILED";
    public static final String SECURITY_RATE_LIMIT_BLOCKED="SECURITY_RATE_LIMIT_BLOCKED";
    public static final String AUTH_ACCOUNT_ACTIVATED="AUTH_ACCOUNT_ACTIVATED", AUTH_PASSWORD_CHANGED="AUTH_PASSWORD_CHANGED", AUTH_PASSWORD_RECOVERY_REQUESTED="AUTH_PASSWORD_RECOVERY_REQUESTED", AUTH_PASSWORD_RECOVERY_COMPLETED="AUTH_PASSWORD_RECOVERY_COMPLETED";
    public static final String STAFF_CREATED="STAFF_CREATED", STAFF_UPDATED="STAFF_UPDATED", STAFF_STATUS_CHANGED="STAFF_STATUS_CHANGED";
    public static final String SETTINGS_CLINIC_UPDATED="SETTINGS_CLINIC_UPDATED", SETTINGS_CATALOG_CHANGED="SETTINGS_CATALOG_CHANGED";
    public static final String APPOINTMENT_CREATED="APPOINTMENT_CREATED", APPOINTMENT_RESCHEDULED="APPOINTMENT_RESCHEDULED", APPOINTMENT_CANCELLED="APPOINTMENT_CANCELLED", APPOINTMENT_STATUS_CHANGED="APPOINTMENT_STATUS_CHANGED";
    public static final String APPOINTMENT_REQUEST_CREATED="APPOINTMENT_REQUEST_CREATED", APPOINTMENT_REQUEST_PROCESSED="APPOINTMENT_REQUEST_PROCESSED", WAITING_ROOM_CHECKED_IN="WAITING_ROOM_CHECKED_IN", WAITING_ROOM_STATUS_CHANGED="WAITING_ROOM_STATUS_CHANGED";
    public static final String APPOINTMENT_REQUEST_IDENTITY_VERIFIED="APPOINTMENT_REQUEST_IDENTITY_VERIFIED", APPOINTMENT_REQUEST_PATIENT_LINKED="APPOINTMENT_REQUEST_PATIENT_LINKED", PATIENT_CREATED_FROM_PUBLIC_APPOINTMENT_REQUEST="PATIENT_CREATED_FROM_PUBLIC_APPOINTMENT_REQUEST";
    public static final String CLINICAL_RECORD_CREATED="CLINICAL_RECORD_CREATED", DOCUMENT_CREATED="DOCUMENT_CREATED", DOCUMENT_VISIBILITY_CHANGED="DOCUMENT_VISIBILITY_CHANGED";
    public static final String PRESCRIPTION_ISSUED="PRESCRIPTION_ISSUED";
    public static final String TREATMENT_PLAN_CREATED="TREATMENT_PLAN_CREATED", TREATMENT_PLAN_UPDATED="TREATMENT_PLAN_UPDATED", TREATMENT_PLAN_APPROVED="TREATMENT_PLAN_APPROVED", TREATMENT_BUDGET_GENERATED="TREATMENT_BUDGET_GENERATED", TREATMENT_BUDGET_APPROVED="TREATMENT_BUDGET_APPROVED", TREATMENT_BUDGET_REJECTED="TREATMENT_BUDGET_REJECTED", TREATMENT_CONSENT_PREPARED="TREATMENT_CONSENT_PREPARED", TREATMENT_CONSENT_ACCEPTED="TREATMENT_CONSENT_ACCEPTED", TREATMENT_CONSENT_REVOKED="TREATMENT_CONSENT_REVOKED", TREATMENT_PROCEDURE_REGISTERED="TREATMENT_PROCEDURE_REGISTERED", TREATMENT_PROCEDURE_COMPLETED="TREATMENT_PROCEDURE_COMPLETED";
    public static final String BILLING_CHARGE_CREATED="BILLING_CHARGE_CREATED", BILLING_PAYMENT_CREATED="BILLING_PAYMENT_CREATED", BILLING_CASH_SHIFT_OPENED="BILLING_CASH_SHIFT_OPENED", BILLING_CASH_SHIFT_CLOSED="BILLING_CASH_SHIFT_CLOSED", BILLING_CASH_MOVEMENT_CREATED="BILLING_CASH_MOVEMENT_CREATED", BILLING_PAYMENT_PLAN_CREATED="BILLING_PAYMENT_PLAN_CREATED", BILLING_PAYMENT_PLAN_CANCELLED="BILLING_PAYMENT_PLAN_CANCELLED", BILLING_DISCOUNT_CREATED="BILLING_DISCOUNT_CREATED", BILLING_CHARGE_VOIDED="BILLING_CHARGE_VOIDED", BILLING_REFUND_CREATED="BILLING_REFUND_CREATED";
}
